### ISSUE TITLE
changing the default size to work on.

### ISSUE THREAD

**Issue by obiwankenoobi** [nirsky/react-native-size-matters#10]
Hello (: 

Let me first say I love your library! It sure make my life easier. 
So my app is developed for 5.5 inch screens first and if I correctly understand, your library is based on 5 inch screens and scale up from there.  Do I have to change some setting to start scaling from 5.5 inch ? or is it all good to use it as is? 
Basically there is somewhere that I need to do something like 5 * 1.1 at the configs or something? 

Thank you!

**Comment by nirsky** [comment]
Hey @obiwankenoobi,
I was thinking maybe integrating [react-native-config](https://github.com/luggit/react-native-config) to allow setting the base guideline dimensions.

What do you think? Could that help with your issue?

**Comment by obiwankenoobi** [comment]
Sorry I forget to close the issue but I just tried the lib as is and it's working great! I didnt looked in the  source code but you did great job, I can confirm that even if your starting position is 5.5' and not 5' like in the docs, it works just great! (:

**Comment by nirsky** [comment]
Cool! Glad it helped you.
I think I'll keep the issue open because that's something I been wanting to do for a while.

**Comment by obiwankenoobi** [comment]
If you do want to do it, then [react-native-config](https://github.com/luggit/react-native-config) I believe will do the trick, just some basic config that let the user pick the starting point of theirs screen. What I liked now about your lib is the amazing simplicity and I hope configs wont make it complicated, so maybe some basic one method like `startingSize(int)` will be awesome! (:

**Comment by nirsky** [comment]
Closing this issue due to:
* Not enough demand
* Adding react-native-config required adding some native code which I don't intend to add
* Adding a `setStartingSize` method or something similar is not good, since most of the StyleSheets are static and will be created before the method will be called

**Comment by raykle** [comment]
Hi Nir,
Thanks for your lib!

My design draft is for 4.7-inch screens, so if an Image is marked as 60 points width in the draft, so what should I do with the scale(?) func? Should I call like this?

```
scale(60 * guidelineBaseWidth / 375)
```

or, how can I config the guidelineBaseWidth?

Thanks.
