### ISSUE TITLE
Merge into react-native-lipstick

### ISSUE THREAD

**Issue by rewieer** [nirsky/react-native-size-matters#13]
Hello guys !

First of all, really thanks you for this work, it's really awesome, i've been using this for many projects and it's reall delightful to use :) 

I've met this problem through many projects and a lot of other problems. There's many lib out there to handle styling in react-native but mixing them up is hard task.

So i created [react-native-lipstick](https://github.com/Rewieer/react-native-lipstick), a flexible lib that mixes up multiple plugins of the same kind (to scale, to have selectors and global variables for example) and allows people to add their own so they can customize their style even more !

Would you guys please collaborate with me on this ? I believe we can really accomplish something huge in term of styling and why not reach the react-community. I've really been struggling with all these available plugins, and working with only one will allow us all to be faster !

Thanks you for reading this :)

**Comment by nirsky** [comment]
Hey @rewieer,
Checked your lib, saw you already referenced and used some methods off my lib.
How can I help any further?
