### ISSUE TITLE
Opening on landscape orientation, rotating to portrait, bigger then normal

### ISSUE THREAD

**Issue by mzhr** [nirsky/react-native-size-matters#14]
I've been using this for a while but have noticed something.

When you develop all components in portrait mode and rotate after objects are rendered, they look good as the components are built using width.

When you render objects while in landscape mode, the react-native `Dimensions` returns width as much higher, and using the scale algorithms, this makes objects bigger.

Now this is fine except when you take into consideration of orientation rotates. Where its overly small when initially portrait and overly large when initially landscape.

I think I may go about this by setting width to the smaller of the 2 dimensions and height to the bigger for it to stay consistent when using the app in both orientations regularly.

@nirsky whats your opinion on this?

**Comment by mzhr** [comment]
If you think this is an issue worth implementing, I created a PR of the fix I made #15.

**Comment by nirsky** [comment]
Hey @mzhr , thanks for your issue and PR.
The `width` and `height` are taken from the `Dimensions` at app launch and are static, meaning that if you launch at portrait and then rotate to landscape your components will keep the same dimensions.

Just wanna make sure I understand, the issue arise **only** when you launch the app at landscape mode, right?
And your PR will basically keep the components' dimensions the same, regardless on what mode the app was launched?

**Comment by mzhr** [comment]
Hi @nirsky thanks for replying.

The main idea behind the issue is that react native `Dimension` treats landscape mode as swapped dimensions (makes sense), meaning the scaling on landscape or portrait will not be consistent.

```javascript
/* eg if a phone of (400wx600h) is portrait mode then the scale method */
const scale = size => w / guidelineBaseWidth * size;
scale(50) = 400 / 350*50 = 57 // if portrait
scale(50) = 600 / 350*50 = 85 // if landscape
```
This effects vertical Scale(portrait value changes) and moderate scale(based on scale) too.

The PR does that yes, because it stops treating it as `{width,height}` and more `{shortDimension, longDimension}` (treats width and height based on portrait mode no matter the orientation).

Where the former leads to scaling inconsistency due to react natives `Dimension` calculation being different based orientation while the latter wont.

**Comment by nirsky** [comment]
Merged your PR (https://github.com/nirsky/react-native-size-matters/pull/15).
Will be included in the next release.
Thanks!!
