### ISSUE TITLE
Dealing with negatives

### ISSUE THREAD

**Issue by mingyjongo** [nirsky/react-native-size-matters#17]
Hello there! I've just gotten started using ScaledSheet and it's awesome to have your functions available in shorthand like this, so kudos!

However! I almost immediately ran into errors in trying to scale a negative margin on an element. It appears your regex doesn't account for a dash in the beginning.

 - For `scale()`:
```javascript
const scaleRegex = /^(\d+(\.\d{1,2})?)@s$/
scaleRegex.test('-5@s') // false
```

add a couple characters........
```javascript
const scaleRegex = /^(-?\d+(\.\d{1,2})?)@s$/
scaleRegex.test('-5@s') // true
```

and voilà!

**Comment by nirsky** [comment]
Thanks @mingyjongo! Missed this one.
Fixed on PR https://github.com/nirsky/react-native-size-matters/pull/18.
Will be included in the next release.
