### ISSUE TITLE
Problem with the landscape rotated apps

### ISSUE THREAD

**Issue by Tiamatmate** [nirsky/react-native-size-matters#27]
In the app that uses vertical orientation mode I used vertical scale and it scaled with the same proportions on every device. Now I have to create an app that is in landscape mode, but it doesn't translate properly on every device (ex. I tried to switch to normal scale and the gap between two views was greater on smaller device?). Am I doing it wrong or is this not possible in landscape mode.

**Comment by nirsky** [comment]
Hey @Tiamatmate,
Not sure I completely I understand your issue, what do you mean by "the gap between two views was greater on smaller device"?
Maybe some screenshots could help understand.

Anyway some clarification regarding landscape mode - `scale` will always scale based on the short dimension and `verticalScale` will always use the long dimension.
So while using portrait mode `verticalScale` will scale based on the device vertical dimension, on landscape mode it will scale based on the device horizontal dimension (a bit confusing I guess).

Does that help?

**Comment by Tiamatmate** [comment]
Hi @nirsky, 
Thanks for the response. Can't share any screenshots because of the NDA. 
The thing is, if the `@vs` or `verticalScale()` always looks for the longer dimensions then scaling should be the same for both modes?
When I developed for portrait mode I had the exact same layout on literally every device size. From really tiny devices to largest tablets. Now the layout is different and I can't figure out why. Can't apply same values for all sizes, regardless of if I use vertical or default scaling.

**Comment by nirsky** [comment]
Sorry, can't think of a solution.
I guess it's related to the usage, because there's nothing fancy in this lib regarding landscape mode.
Let's keep it open for a while, maybe someone stumbled upon this and can help :)

**Comment by valmirduraku** [comment]
I had this problem too. Tweaked it a little.

`import { Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

//Guideline sizes are based on standard ~5" screen mobile device
const guidelineBaseWidth = 350;
const guidelineBaseHeight = 680;

let deviceWidth = width;
let deviceHeight = height;

if (width > height) {
  deviceWidth = height;
  deviceHeight = width;
}

const scale = size => (deviceWidth / guidelineBaseWidth) * size;
const verticalScale = size => (deviceHeight / guidelineBaseHeight) * size;
const moderateScale = (size, factor = 0.5) =>
  size + (scale(size) - size) * factor;

export { scale, verticalScale, moderateScale };
`

**Comment by valmirduraku** [comment]
Hi @nirsky,
Maybe you have fixed it but for future devs encountering this issue, I've made some changes to the library itself and it works on landscape too.
https://gist.github.com/valmirduraku/1b011b5070ad6143c8e72fc1f80bc9a0

**Comment by nirsky** [comment]
Hey @valmirduraku, thanks for your comment!
I already have similar code on the [scaling-utils](https://github.com/nirsky/react-native-size-matters/blob/master/lib/scaling-utils.js) file:
```
const { width, height } = Dimensions.get('window');
const [shortDimension, longDimension] = width < height ? [width, height] : [height, width];
```

So I suppose that's not the issue @Tiamatmate is experiencing..

**Comment by valmirduraku** [comment]
Hi @nirsky,
I didn't have the version of your code so I changed it. Maybe @Tiamatmate doesn't have it too. Let's wait for a response from him.

**Comment by nirsky** [comment]
I'm gonna go ahead and closed this for now.
