### ISSUE TITLE
How to use this with styled-components?

### ISSUE THREAD

**Issue by Joshandrews43** [nirsky/react-native-size-matters#35]
Currently looking to use this for my production app to extend it to ipad, but the app is styled with styled components. Is there a way to integrate this with styled components? I think this is the cleanest solution I've found for RN adaptability.

**Comment by nirsky** [comment]
While `ScaledSheet` can't be used with styled-components, there's no problem using the scale utils.
Example:

```js
import styled from 'styled-components/native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

const Container = styled.View`
    width: ${scale(100)};
    height: ${verticalScale(180)};
    background-color: papayawhip;
    margin: ${moderateScale(15)};
    padding: 5;
`;
```
