### ISSUE TITLE
Disable scaling on mobile devices

### ISSUE THREAD

**Issue by knezevicdev** [nirsky/react-native-size-matters#39]
I'm looking for functionality to disable scaling entirely on mobile (or just mobile portrait) devices so that library use functions only on the tablet. I've explored source code and haven't found anything like that.

Do you find that interesting? I would like to help with the implementation.

**Comment by jay-jlm** [comment]
@knezevicdev https://github.com/react-native-community/react-native-device-info#getDeviceType
