### ISSUE TITLE
Should be able to set reference size

### ISSUE THREAD

**Issue by cipriancaba** [nirsky/react-native-size-matters#4]
Right now, values are hardcoded in https://github.com/nirsky/react-native-size-matters/blob/master/lib/scalingUtils.js

//Guideline sizes are based on standard ~5" screen mobile device
const guidelineBaseWidth = 350;
const guidelineBaseHeight = 680;

To explain my use case, I finished the design using iphone 8, 8S and iPad references.. everything looks great, however, I learned that I need to support 5s (which has a screen width of 320)

**Comment by nirsky** [comment]
Hey @cipriancaba, what's the outcome on 5s?
On this case the scaling utils should scale down your design since the screen is smaller. 
This is the expected output for a 5S device.

The sizes are hardcoded since everything in this library is static, there isn't some kind of init method.
Also, everything must stay static to enjoy the performance benefits of a static StyleSheet - according to the [official docs](https://facebook.github.io/react-native/docs/stylesheet.html):

> Performance:
> * Making a stylesheet from a style object makes it possible to refer to it by ID instead of creating a new style object every time.
> * It also allows to send the style only once through the bridge. All subsequent uses are going to refer an id (not implemented yet).

**Comment by cipriancaba** [comment]
Hey, thanks for the quick reply.. [here](https://jsbin.com/somamahora/edit?html,js,console,output) is an example of what goes wrong.. I am using the library to scale a container of 350 width on all range of devices but this falls outside of bounds for 5s

```
// iPhone 5s
const width = 320
const height = 568

//Guideline sizes are based on standard ~5" screen mobile device
const guidelineBaseWidth = 350;
const guidelineBaseHeight = 680;

const scale = size => width / guidelineBaseWidth * size;
const verticalScale = size => height / guidelineBaseHeight * size;
const moderateScale = (size, factor = 0.5) => size + ( scale(size) - size ) * factor;

console.log(scale(350)) // 320 -> still ok
console.log(moderateScale(350, 0.1)) // 347 -> out of bounds (only 320 width)
```

**Comment by nirsky** [comment]
@cipriancaba good point! Never thought about this case.
I must say when going full width I'd usually go with stuff like `flex: 1`, `width: '100%'` or `alignSelf: 'stretch'`, so I have never encountered that.

Here are some options I had in mind to fix this:

```js
//Option 1:
const moderateScale = Math.min((size, factor = 0.5) => size + ( scale(size) - size ) * factor, width)

//Option 2:
const moderateScale = (size, factor = 0.5, misSize) => {
    const result = size + ( scale(size) - size ) * factor;
    return misSize ? Math.min(minSize, result) : result;
};

//Option 3
const scale = (size, baseWidth = guidelineBaseWidth) => width / baseWidth * size;
const moderateScale = (size, factor = 0.5, baseWidth = guidelineBaseWidth) => size + ( scale(size,baseWidth) - size ) * factor;
```

I'd be happy to hear your opinion, what you think will work best for you?

**Comment by cipriancaba** [comment]
I made  a PR with a proposed change.. it's not perfect since it fails for really big values passed to ms

**Comment by nirsky** [comment]
I decided to close this issue since setting full screen width for a View if not a recommended practice (like I mentioned, for this cases I'd use `flex: 1`, `width: '100%'` or `alignSelf: 'stretch'`).
I prefer to keep the formula strict.
