### ISSUE TITLE
What are the best practices for font scaling?

### ISSUE THREAD

**Issue by SrBrahma** [nirsky/react-native-size-matters#44]
Hey, just started using this lib!

For fontsize, should I use scale, verticalScale or moderateScale? If moderateScale (as the examples uses), how should I choose the size and the factor? Which one should I 'fix' first? Is there some kind of "equation" to find the magic proportion?

I just want to make my app look good everyhere hehe

Thanks!

**Comment by nirsky** [comment]
Hey, so there's no right and wrong, each one can go with what fits best for him.  
For me personally, I found `moderateScale` with a scale factor of 0.3 to work best for me.  
Does this help?
