### ISSUE TITLE
App breaks if importing from " /extend" with latest react-native-dotenv module

### ISSUE THREAD

**Issue by MartinZAtanasov** [nirsky/react-native-size-matters#54]
This case results in error message: **module fs does not exist in the haste module map react native**
Latest react-native-dotenv version requires to be imported differently.

  _// old import of dotenv
  **import { SIZE_MATTERS_BASE_WIDTH, SIZE_MATTERS_BASE_HEIGHT } from 'react-native-dotenv'**

  _// new import of dotenv
  **import { SIZE_MATTERS_BASE_WIDTH, SIZE_MATTERS_BASE_HEIGHT } from '@env'**

**Comment by nirsky** [comment]
Thanks. Didn't realize the API changed.
Will fix it soon.

**Comment by p4kaidu** [comment]
I tried to fix it in PR #55

**Comment by nirsky** [comment]
Thanks @p4kaidu, your PR was merged.
Released a new version - [v0.4.0](https://github.com/nirsky/react-native-size-matters/releases/tag/v0.4.0) with the lastest changes.
