### ISSUE TITLE
How to setup changing the default Sizes

### ISSUE THREAD

**Issue by hungdev** [nirsky/react-native-size-matters#63]
Thank for your library. @nirsky nirsky
I don't know what I'm missing.
install lib: `npm install babel-plugin-dotenv-import`
then add `dotenv-import` to `babel.config.js`, here is mine:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      "module-resolver",
      {
        root: [
          "./src"
        ],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          "app": "./src",
          "src": "./src",
          "components": "./src/components",
          "reducers": "./src/reducers",
          "config": "./src/config",
          "assets": "./src/assets",
          "screens": "./src/screens",
          "utils": "./src/utils",
          "themes": "./src/themes",
          "navigation": "./src/appNavigation",
          'i18n': "./src/i18n"
        }
      }
    ],
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true
      }
    ],
    ["dotenv-import", {
      "moduleName": "@env",
      "path": ".env",
      "blacklist": null,
      "whitelist": null,
      "safe": false,
      "allowUndefined": false
    }]
  ],
};
```

then create `.env` file with content:
```
SIZE_MATTERS_BASE_WIDTH=375
SIZE_MATTERS_BASE_HEIGHT=812
```

then change import like this: `import { ScaledSheet, moderateScale } from 'react-native-size-matters/extend';`

But I got error like this
<p align="center">
  <img src="https://user-images.githubusercontent.com/12009276/112712788-1b901280-8f04-11eb-83ec-82df9dadea8d.png" width=300/>
</p>

I don't know what I'm missing, could you tell me what I missed?
Thank you so much.

**Comment by nirsky** [comment]
Hey, are you using TypeScript?
Might be related - https://github.com/tusbar/babel-plugin-dotenv-import/issues/113
If so, first try using [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) in your tsconfig, to see if it eliminates the issue.

**Comment by hungdev** [comment]
Thank for your reply, @nirsky 
I dont use typescript

**Comment by nirsky** [comment]
I see. I'll try to reproduce it locally on my machine then.

**Comment by nirsky** [comment]
Hey, I couldn't reproduce the issue on my machine.
Seems to be working perfectly.
Unfortunately, there's nothing more I can do to assist without being able to debug it myself 🤷🏼‍♂️ 

I suggest researching a bit more online or open an issue in [babel-plugin-dotenv-import](https://github.com/tusbar/babel-plugin-dotenv-import/issues).

**Comment by hungdev** [comment]
@nirsky thank you. I dont understand why, maybe due to cache. Now it worked.
