### ISSUE TITLE
Possible to use it with tailwind-rn library?

### ISSUE THREAD

**Issue by niklasgrewe** [nirsky/react-native-size-matters#64]
Hi, thanks for your effort and your great explanitions about size matters in react native 👍 

In my RN-Project, i am using the library [tailwind-rn](https://github.com/vadimdemedes/tailwind-rn), to support tailwind classes. Is there a way to combine this with your library? I am a newcomer to React Native. If there is a way, could you show me how can i implement it?

**Comment by nirsky** [comment]
Unfortunately, it's not possible to apply size-matters on the tailwind utilities directly, but it is possible to do some kind of combination.

Example:
```jsx
import React from 'react';
import { SafeAreaView, View, Text } from 'react-native';
import { scale, moderateScale } from 'react-native-size-matters';
import tailwind from 'tailwind-rn';

const App = () => (
  <View style={{ ...tailwind('bg-blue-200 px-3 py-1 rounded-full'), margin: scale(5) }}>
    <Text style={{ ...tailwind('text-blue-800 font-semibold'), fontSize: moderateScale(13) }}>
      Hello Tailwind and Size Matters!
    </Text>
  </View>
);

export default App;

```
