### ISSUE TITLE
"Spread types may only be created from object types" Typescript error

### ISSUE THREAD

**Issue by ilyakar** [nirsky/react-native-size-matters#67]
Hi, I've been getting this error since switching to ScaledSheet from StyleSheet.

![image](https://user-images.githubusercontent.com/1760709/131350490-2914a5b9-d43d-4af1-bf92-4a90397743d7.png)

**Comment by ilyakar** [comment]
It works. But Typescript is complaining :(

**Comment by bwnstck** [comment]
same question here :) 💨

**Comment by nirsky** [comment]
@bwnstck So I understand this is a react-native issue, rather than a react-native-size-matters issue?
