### ISSUE TITLE
Using react-native-config instead of babel config

### ISSUE THREAD

**Issue by amerllica** [nirsky/react-native-size-matters#72]
To have a better experience of `extend` using [`react-native-config`](https://www.npmjs.com/package/react-native-config) would be easy and awesome for developers, I have read [here](https://github.com/nirsky/react-native-size-matters/blob/master/examples/change-guideline-sizes.md) but I couldn't config that for my project. instead of this doc, I think using [`react-native-config`](https://www.npmjs.com/package/react-native-config) will make an easier situation for a developer.

**Comment by nirsky** [comment]
What's wrong with the current setup using [babel-plugin-dotenv-import](https://github.com/tusbar/babel-plugin-dotenv-import)?
I actually examined all the alternatives in the past (react-native-config, react-native-dotenv) and came to a conclusion the babel plugin is the most easy to set up, doesn't require any peer dependencies and has the minimal footprint.

**Comment by amerllica** [comment]
I had a problem with `babel-plugin-dotenv-import` and couldn't setup it, so I changed `@env` to `react-native-config` and it became ok, I used **patch-package** to keep it in my project. if you think it is not necessary, tell me to close issue and it's PR.

**Comment by nirsky** [comment]
I'm happy with the current setup, but would like to give full attention to this.
What issues did you have with `babel-plugin-dotenv-import`? Is it something un-fixable?

**Comment by amerllica** [comment]
That's ok dear @nirsky, If you are happy, I will close it now. because I do not remember what's my problem, I strictly followed up on the docs but in the end, I faced a weird issue, I changed the `@env` to `react-native-config` and it worked. so now let's close the issue and its PR.
