### ISSUE TITLE
"No unused styles" eslint rule not working with ScaledSheet

### ISSUE THREAD

**Issue by ilyakar** [nirsky/react-native-size-matters#75]
This rule works well when I'm using the default `StyleSheet.create({` function.
```
'react-native/no-unused-styles': 'warn',
```

But it doesn't work with `ScaledSheet.create({`.

Any ideas how I can get react-native-size-matters to play with with Eslint / Eslint react native plugin?
https://github.com/Intellicode/eslint-plugin-react-native

**Comment by nirsky** [comment]
Looking at their code - the lint rule is coupled to the original StyleSheet.
To have this support with react-native-size-matter you'd need to write your own linting rule/plugin.
