### ISSUE TITLE
Where to use which function??

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [nirsky/react-native-size-matters#86]
I am little confused which to use for fontSize scale, moderateScale, moderateVerticalScale or verticalScale for responsiveness, also it this lib suitable for android apps??
In some android using these functions makes fontSize very bigger.

**Comment by SMARTMICROWORLD** [comment]
> I am little confused which to use for fontSize scale, moderateScale, moderateVerticalScale or verticalScale for responsiveness, also it this lib suitable for android apps??

In some android using these functions makes fontSize very bigger.

**Comment by nirsky** [comment]
Suitable for Android apps.
There aren't exact guidelines on where to use what, it's a matter of design and personal taste.

You can read more in the blog post: https://medium.com/soluto-engineering/size-matters-5aeeb462900a
