### ISSUE TITLE
Image size also matter

### ISSUE THREAD

**Issue by Norfeldt** [nirsky/react-native-size-matters#9]
Struggling with getting the Android app load all my images because I have been lazy and just dropped some big ass images in.. now I'm being punished.. 

Could this repo also give some ninja tricks on how to deal with images?

**Comment by szholdiyarov** [comment]
@Norfeldt what is the problem? the size of the images? could you drop some of the image examples here?

**Comment by Norfeldt** [comment]
I had some cards with some text and a picture below. I'm really bad at styling images but I had to set the width and height manually. Would be handy if flex would do the trick, but not defining the width and height was causing some problems. Setting them to undefined didn't work...

**Comment by Norfeldt** [comment]
If you need to see my code then it's at https://github.com/Norfeldt/LionFood_FrontEnd

**Comment by nirsky** [comment]
@Norfeldt I hope my previous comment helped.
Unfortunately, I don't have any other tricks for scaling images, other than of course using the scaling utils to change hard coded width and height of an image.

Closing this issue for now.
